### ISSUE TITLE
Interpretation, Spelling Errors and Consistency

### ISSUE THREAD

**Issue by BrianLambert118** [labopm/HCD-Guides#10]
Design in Government (Paragraph 3):

Each of these examples has roots in laws, policies, and initiatives from legislatures, agencies, and other government bodies, but growing the ideas from their roots into functional products, services, or systems require a design process — and that process is more impactful when it is **conscious, careful, and intentional, or not.**  Not sure what we are trying to say when we add or not to the sentence.

**Comment by anatecture** [comment]
Hi Brian! Congratulations on logging your first issue, and thank you! 

Two things:
1) Please log each issue separately and use the labels in the right hand column on this page to label them. This allows us to sort and track issues according to type and content. 
2) Please link to all of the pages for which you're logging an issue. This allows the person who might address the issue to find the trouble spot easily. 

I'll label your first issue in this thread, and then you can follow with the other two.

**Comment by anatecture** [comment]
In regards to your first issue: 

> Each of these examples has roots in laws, policies, and initiatives from legislatures, agencies, and other government bodies, but growing the ideas from their roots into functional products, services, or systems require a design process — and that process is more impactful when it is conscious, careful, and intentional, or not. Not sure what we are trying to say when we add or not to the sentence.

The meaning behind the use of the words "or not" here is to surface the fact that many products, services, and systems that have been made and deployed in the public sector have not, in fact been made intentionally or consciously. Instead, they have been implemented as a reaction to a policy or mandate, without much consideration to systematic needs, intersystem conflicts, or participant sentiments, needs, or prior work flow. Thoughts?

**Comment by BrianLambert118** [comment]
Thanks for the clarification. I went in and separated the issues but i am not able to assign labels.

**Comment by anatecture** [comment]
thanks for separating! glad the clarification worked, and no, as we found yesterday; you all can't label issues — good to know for sure.
