### ISSUE TITLE
Spelling/Grammar Errors

### ISSUE THREAD

**Issue by pooja-nair-opm** [labopm/HCD-Guides#4]
VA PATS Case In Point: "were willing to work more closely with the medical"

**Comment by pooja-nair-opm** [comment]
USAJobs Case in Point: "No feature of this siwte appeared to the public "

**Comment by pooja-nair-opm** [comment]
Page 10 Paragraph 2 --> Measurements

**Comment by pooja-nair-opm** [comment]
Page 10 Paragraph 3 --> A workable

**Comment by pooja-nair-opm** [comment]
Page 13 Paragraph 4 --> Most often

**Comment by pooja-nair-opm** [comment]
Page 28 Paragraph 1 --> Constrained

**Comment by pooja-nair** [comment]
Page 24 Paragraph 1: interactive

**Comment by pooja-nair** [comment]
Page 25 Paragraph 2: specialty

**Comment by pooja-nair** [comment]
Page 25 Paragraph 4: opportunities

**Comment by pooja-nair** [comment]
Page 27 Paragraph 3: about how

**Comment by pooja-nair** [comment]
Page 27 Paragraph 3: about the natural

**Comment by pooja-nair** [comment]
Page 43 Paragraph 5: Infinite

**Comment by pooja-nair** [comment]
Page 44 Paragraph 3: Participants

**Comment by pooja-nair** [comment]
Page 45 Paragraph 3: acceptable

**Comment by pooja-nair** [comment]
Page 46 Paragraph 3: awareness

**Comment by pooja-nair** [comment]
Page 47 Paragraph 1: primarily

**Comment by pooja-nair** [comment]
Page 49 Paragraph 1: Design

**Comment by pooja-nair** [comment]
Page 16 Side: Derived

**Comment by pooja-nair** [comment]
Page 18 Paragraph 3: Evaluate

**Comment by pooja-nair** [comment]
Page 14 Paragraph 3: Unwieldy

**Comment by pooja-nair** [comment]
Page 17 Paragraph 2: Vacuum

**Comment by pooja-nair** [comment]
Page 15 Paragraph 3: Participants (3 times)

**Comment by pooja-nair** [comment]
Page 31 Paragraph 1: Description

**Comment by pooja-nair** [comment]
Page 16 Paragraph 4: Empathy

**Comment by pooja-nair** [comment]
Page 38 Paragraph 4: references

**Comment by pooja-nair** [comment]
Page 38 Ref: Courses

**Comment by pooja-nair** [comment]
Page 40 Paragraph 1: Understanding

**Comment by pooja-nair** [comment]
Page 19 Paragraph 3: ecosystem

**Comment by pooja-nair** [comment]
Page 34 Paragraph 1: Holistically

**Comment by pooja-nair** [comment]
Page 22 Paragraph 1: Groups

**Comment by pooja-nair** [comment]
Page 22 Paragraph 1: That

**Comment by pooja-nair** [comment]
Page 23 Paragraph 1: Their

**Comment by pooja-nair** [comment]
Page 23 Paragraph 2: Closely

**Comment by pooja-nair** [comment]
Page 23 Paragraph 2: The

**Comment by pooja-nair** [comment]
Page 10 Paragraph 2: Measurements

**Comment by pooja-nair** [comment]
Page 10 Paragraph 3: a workable

**Comment by pooja-nair** [comment]
Page 13 Paragraph 4: Most often

**Comment by pooja-nair** [comment]
Page 28 Paragraph 1: Constrained

**Comment by pooja-nair** [comment]
Page 10 Paragraph 2: Design

**Comment by pooja-nair** [comment]
Page 10 Paragraph 2: evaluation

**Comment by pooja-nair** [comment]
Page 10 Paragraph 5: practitioners

**Comment by pooja-nair** [comment]
Page 3 Paragraph 2: Original

**Comment by pooja-nair** [comment]
Page 5 Paragraph 2: evaluate

**Comment by pooja-nair** [comment]
Page 5 Paragraph 3: technical
