### ISSUE TITLE
grammatical error 

### ISSUE THREAD

**Issue by AKijanski** [labopm/HCD-Guides#8]
in the Services section near the bottom of the page before the Lab VEO diagram this sentence does not read correctly:

This program also an opportunity for VEO and The Lab at OPM to build an HCD capacity

**Comment by anatecture** [comment]
Hi Adam - can you link to the page?

**Comment by anatecture** [comment]
and congratulations on your first issue log! very cool.

**Comment by AKijanski** [comment]
Yes.  The links work but they change the guide page

Respectfully,

Adam Kijanski, LCSW, CCM
Chief, VBA/BVA Division
VA Benefits Experience Directorate (VABX)
Veterans Experience Office
Department of Veteran Affairs

USSOCOM Headquarters
Cell:   813-610-9574
Fax: 813-826-6039
Adam.Kijanski@va.gov<mailto:Adam.Kijanski@va.gov>
Adam.Kijanski@socom.mil<mailto:Adam.Kijanski@socom.mil>

CLICK HERE TO DOWNLOAD THE VA WELCOME KIT<https://www.va.gov/welcome-kit/>
Whether you’re just getting out of the service or you’ve been a civilian for years now, the VA Welcome Kit can help guide you to the benefits and services you’ve earned.

**Comment by anatecture** [comment]
sorry - "the link works but they change the guide page" can you explain that? also, when you reply via email, it posts the whole thread. please reply in github.

**Comment by AKijanski** [comment]
ok

Respectfully,

Adam Kijanski, LCSW, CCM
Chief, VBA/BVA Division
VA Benefits Experience Directorate (VABX)
Veterans Experience Office
Department of Veteran Affairs

USSOCOM Headquarters
Cell:   813-610-9574
Fax: 813-826-6039
Adam.Kijanski@va.gov<mailto:Adam.Kijanski@va.gov>
Adam.Kijanski@socom.mil<mailto:Adam.Kijanski@socom.mil>

CLICK HERE TO DOWNLOAD THE VA WELCOME KIT<https://www.va.gov/welcome-kit/>
Whether you’re just getting out of the service or you’ve been a civilian for years now, the VA Welcome Kit can help guide you to the benefits and services you’ve earned.

**Comment by anatecture** [comment]
I think I understand: this comment is in regards to your other issue log: the one where you ask that links open in new tabs. Is that correct? 

Regarding this issue: I was asking if you could link to the page where you found this grammatical error?

**Comment by AKijanski** [comment]
Here is the link to the page with the grammar issue i mentioned:
https://hcd-design-phase-concept-guide.netlify.com/services.html

> This program also an opportunity for VEO 

> and                 The Lab at OPM to build an HCD capacity building program that could be leveraged by other Agencies in support of the President’s

**Comment by anatecture** [comment]
perfect - thanks.

**Comment by anatecture** [comment]
addressed and resolved; thank you @AKijanski!
